In [3]:
# Task: Create a credit risk model, which estimates the probability of default for every personal account
# Take the raw dataset and prepare it for the model planned to be run
# The goal is to obtain a clean and preprocessed dataset

In [4]:
# Step 1: Changing the currency of the dataset from Dollars to Euros
# Step 2: Every categorical variable must be quantified; change any text columns into numbers
# There is need to be extremely risk-averse and distrustful; hence missing information suggests foul play for this loan app
# The loan information is from a csv file called loan-data.csv

In [5]:
# Open the file with a text editor like Notepad ++ to know the delimiter of the dataset
# Examining the file, the rows can be referred to as Accounts, Candidates, or Application

In [6]:
# First, import numpy
import numpy as np

In [7]:
# Use this print_options to improve the way the output is shown on the screen.
# The 'suppress = True' argument will stop numpy from using scientific notations to represent numbers
# Precision = 2 will display only the first 2 digits after the decimal
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

In [8]:
# Storing the whole data into a variable called raw_data_np
# First use np.loadtxt; there are missing values if it return error message, then use np.genfromtxt
# Apply remove_header since the first row is not a number (nan)
# Set autostrip = True to remove excess white space which can distort the columns
raw_data_np = np.genfromtxt("loan-data.csv", delimiter = ';',
                            skip_header =1, autostrip = True)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [9]:
# Checking for missing elements (incomplete data)
np.isnan(raw_data_np).sum()

# The output showed there are 88,005 missing elements in the dataset

88005

In [10]:
# Create two temporary variables: temporary_fill and temporary_mean (mean for every column)
# The maximum variable in the dataset will form the temporary_fill
temporary_fill = np.nanmax(raw_data_np) + 1
temporary_mean = np.nanmean(raw_data_np, axis = 0)

# Note: The warning in the output showed we might be overlooking something (some columns contain text data)

C:\Users\hp pc\AppData\Local\Temp\ipykernel_4900\3938352329.py:4: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np, axis = 0)


In [11]:
# Computing the temporary_mean showed 8 columns contain strings
temporary_mean 

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [12]:
# Split the dataset into 2; one containing the numeric values, and the other strings
# Before that, extract the minimum and the maximum values for each column in the dataset

# Create a list

temporary_stats =np.array([np.nanmin(raw_data_np, axis = 0), temporary_mean, np.nanmax(raw_data_np, axis = 0) ])

# The 2 warnigs in the output indicates we are plugging in empty slices. Note they are texts and not empty

C:\Users\hp pc\AppData\Local\Temp\ipykernel_4900\876191102.py:6: RuntimeWarning: All-NaN slice encountered
  temporary_stats =np.array([np.nanmin(raw_data_np, axis = 0), temporary_mean, np.nanmax(raw_data_np, axis = 0) ])


In [13]:
temporary_stats
# The output consists of a 2D array that holds three 1-D array stacked on top of each other
# The order is min, mean, and max

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [14]:
# Splitting the dataset into numeric and strings
# Identifying columns with strings
columns_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [15]:
# Identifying columns with numeriacal values
columns_numeric = np.argwhere(np.isnan(temporary_mean)==False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [16]:
# Re-import the original dataset as 2 seperate arrays using usecols
loan_data_strings = np.genfromtxt("loan-data.csv", 
                                  delimiter = ';',
                                  skip_header =1,
                                  autostrip = True,
                                  usecols = columns_strings,
                                  dtype = np.str)
loan_data_strings


C:\Users\hp pc\AppData\Local\Temp\ipykernel_4900\3968442672.py:7: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [17]:
# Use the temporary_fill computed earlier as filling_values for the missing data
loan_data_numeric = np.genfromtxt("loan-data.csv", 
                                  delimiter = ';',
                                  skip_header =1,
                                  autostrip = True,
                                  usecols = columns_numeric,
                                  filling_values = temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [18]:
# Before working on the contents of the table, store the headers of each column in order not to lose track of the info stored on each column
# Set skip_footer to the number of rows in raw_data_np
header_full = np.genfromtxt("loan-data.csv", 
                                  delimiter = ';',
                                  skip_footer = raw_data_np.shape[0],
                                  autostrip = True,
                                  dtype = np.str)
header_full

C:\Users\hp pc\AppData\Local\Temp\ipykernel_4900\1013414701.py:7: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [19]:
# Put the headers into 2 variables; each one holding the names of the column which contains string data or numeric data
# It will create two new variables which will serve as headers
header_strings, header_numeric = header_full[columns_strings], header_full[columns_numeric]

In [20]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [21]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [22]:
# Create checkpoints
# Checkpoints are places throughout our code where we store a copy of our dataset (or only part of it)
# This is to avoid losing a lot of progress if we accidentally override the variables we've been working with
# It is a failsafe we can rely on

In [23]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return (checkpoint_variable)

In [24]:
checkpoint_test = checkpoint("checkpoint_test", header_strings, loan_data_strings)

In [25]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [26]:
# Checking if checkpoint variables are equal to the earlier variables, use the equal function
np.array_equal(checkpoint_test['data'], loan_data_strings)

True

In [27]:
# Rename the first header from 'Issue_d' to 'Issue_date' to be more descriptive 
header_strings[0] = "Issue_date"
header_strings

array(['Issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [28]:
#The output showed a pattern: all months are represented by 3 alphabets, and all are in 2015
loan_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [29]:
# Check if the pattern cut across all variables in the columns
np.unique(loan_data_strings[:,0])

#The output showed similar pattern, and there is a missing data before April-15

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [30]:
# Remove -15 since its common across the column
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0], "-15")

In [31]:
# Check again to confirm its not containing the year
# This results in using less memory
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [32]:
# Store the months values as integers to achieve usage of less memory
# create an array to show all the months including the missing value
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [33]:
# Then set Jan for 1, Feb for 2, etc
for i in range(13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0]== months[i], i, loan_data_strings[:,0])

In [34]:
# Check again if there are no longer empty space
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [35]:
# Display header_string again to check all the columns heading
header_strings

array(['Issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [36]:
# The next column is loan_status
loan_data_strings[1]

array(['0', 'Current', '36 months', 'A', 'A5', 'Source Verified',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'], dtype='<U69')

In [37]:
# Check the values in the columns
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [38]:
# Call the size attribute of the array to get the number of unique elements in the column
np.unique(loan_data_strings[:,1]).size

9

In [39]:
# We can use np.where() to assign a different number to each of the 9 status but regressions only care if the candidate is in a stable financial condition
# Hence split all possible values into either 'good' or 'bad'
# Acccounts with 'Current', 'Fully Paid', 'In Grace Period', and 'Issued' will be grouped as 'Good'
# 'Charged Off', empty '', and 'Default' will be grouped into 'Bad'
# Short period latency 'Late (16 - 30 days)'' will be grouped as 'Good' while longer period (31 - 120 days) is 'Bad'
# 1 will be used to represent 'Good' and 0 for 'Bad'

In [40]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [41]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1], status_bad), 0,1)

In [42]:
# To check if the number 0 and 1 have been properly assigned 
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [43]:
# Check the next column header
header_strings


array(['Issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [44]:
loan_data_strings[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [45]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [51]:
# Strip the 'months' since its common
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2], " months")

In [52]:
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [53]:
# Change the header name to be more descriptive
header_strings[2] = "term_months"

In [54]:
# Assign 60 to the missing values. 60 is the highest value in the column, hence we assume the worst in cases of missing values
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == '', '60', loan_data_strings[:,2])

In [55]:
# Check the content of the term_month array
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

In [56]:
# You can either assign 1 and 0 fro the '36' and '60' or leave it as it is

In [57]:
# Check the next header
header_strings

array(['Issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [58]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [59]:
# We examine column "sub_grade" because they look related
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [61]:
# For every element in 'Grade' we have five elements in 'sub_grade', hence info in 'grade' column can be obtained from 'sub_grade' column
# Use iteration to fill the missing values in 'sub_grade
# Assign the worst of sub_grade i.e. 5 to missing values
for i in np.unique(loan_data_strings[:,3])[1:] : loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '')
                                                                                   & (loan_data_strings[:,3] == i),
                                                                                    i + '5', loan_data_strings[:,4]
                                                                                   )

In [62]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [63]:
# The output is the same, hence we still have missing data because there are still rows where we have neither the 'sub_grade' nor the 'grade'
# Count the number of instances we have the missing value
np.unique(loan_data_strings[:,4], return_counts = True) # the result showed 9 instances of missing sub_grades

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [64]:
# Create a new category lower than G5 and assign to the missing values
loan_data_strings[:,4] = np.where(loan_data_strings[:,4] == '', "H1", loan_data_strings[:,4])

In [66]:
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [67]:
# We no longer need the 'grade' column since all info can be found in 'sub_grade', hence delete 'grade' column
loan_data_strings = np.delete(loan_data_strings, 3, axis = 1)

In [68]:
# 'Grade' column is now the fourth column
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [69]:
# Effect the change in the header
header_strings = np.delete(header_strings, 3)

In [70]:
header_strings[3]

'sub_grade'

In [71]:
# Assign numbers to each of the sub_grade from A1 to H1
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [72]:
keys = list(np.unique(loan_data_strings[:,3]))
values = list(range(1, np.unique(loan_data_strings[:,3]).shape[0] + 1))
dict_sub_grade = dict(zip(keys, values))

In [74]:
# The keys above include all the unique sub_grades
# The values include all the integers betweeen 1 and 36 that will be assigned to each sub_grade
# The zip function is used to create a dictionary that matches these values

dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [75]:
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i, dict_sub_grade[i],
                                      loan_data_strings[:,3])

In [77]:
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [78]:
# Call header_strings to see the name of the next column
header_strings

array(['Issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [79]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [80]:
# We assume the missing value is equavalent to 'Not Verified'

In [81]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') | (loan_data_strings[:,4] == 'Not Verified'),0,1)

In [82]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

In [83]:
# The next column is url
np.unique(loan_data_strings[:,5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [86]:
# The url address is identical to all except loan_id, hence we can strip all leaving only the id array of numbers stored as strings
loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=' )

In [89]:
loan_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [87]:
# Recall the first column in the full header is called id. Let's check if it is same with the id above

header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [90]:
# Check the contents of the id column

loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [91]:
# Check if loan_data_strings[:,5] is same as loan_data_numeric[:,0]
# First convert the values into integers
loan_data_strings[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [92]:
loan_data_numeric[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [93]:
np.array_equal(loan_data_strings[:,5].astype(dtype = np.int32), loan_data_numeric[:,0].astype(dtype = np.int32))

True

In [94]:
# The fact that the two arrays are identical showed that the url column does not hold any additional information that cannot be extracted in id column
# We will then get rid of the url column

loan_data_strings = np.delete(loan_data_strings, 5, axis = 1)

In [95]:
# Also delete the url column header
header_strings = np.delete(header_strings,5)

In [96]:
# To confirm it was successfully deleted, call column 5
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [97]:
header_strings

array(['Issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [98]:
# The last column to work on is addr_state. Change the name to be more relatable

header_strings[5] = "state_address"

In [99]:
# Check the unique values in the state_address column

np.unique(loan_data_strings[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [100]:
# The state_address column showed USA states' abbreviations, and also empty space (missing value)

# Checking the size of the array showed 50 unique values which is exactly the number of states in the US
np.unique(loan_data_strings[:,5]).size

50

In [101]:
# Checking the number of occurence per state 
np.unique(loan_data_strings[:,5], return_counts = True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [102]:
# States are listed alphabetically in the above output but the number of occurence per state did not follow descending/ascending order
# Apply below function to return the counts per state in descending order

In [103]:
states_names, states_count = np.unique(loan_data_strings[:,5], return_counts = True)
states_count_sorted = np.argsort(-states_count)
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [104]:
# The output above showed most of the account comes from highly populated and wealthy states like CA, NY, TX, and FL
# The 500 counts for missing address showed higher number of counts than any of the other 45 states
# We have few data for too many states to examine each one individually
# Assigning a unque value to each state will allow outliers to have a big influence on the coefficients
# The states with fewer applications will be more vulnerable to have their coefficients affected by outliers
# To solve the problem, group the states according to common characteristics like geographic location

In [105]:
# Assign zero to missing values
loan_data_strings[:,5] = np.where(loan_data_strings[:,5] == '', 0,
                                  loan_data_strings[:,5])

In [110]:
# Now group the states
states_west = np.array(['ID', 'MT', 'NV', 'UT', 'WY', 'AK', 'CA', 'HI', 'OR', 'WA', 'AZ', 'CO', 'NM'])
states_south = np.array(['OK', 'TX', 'AR', 'LA', 'MS', 'TN', 'AL', 'KY', 'GA', 'FL', 'WV', 'VA', 'NC','SC','DC','MD','DE'])
states_midwest = np.array(['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO', 'WI', 'IL', 'MI', 'IN', 'OH'])
states_east = np.array(['PA', 'NY', 'VT', 'NH', 'ME', 'MA', 'RI', 'CT', 'NJ'])

In [111]:
# Assign 1 to states_west, 2 to states_south, 3 to states_midwest, and 4 to states_east
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_west), 1,
                                  loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_south), 2,
                                  loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_midwest), 3,
                                  loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_east), 4,
                                  loan_data_strings[:,5])

In [112]:
# Call the unique values to check if the numbers have been assigned appropriately

np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [113]:
# All string data have been converted into numeric values stored as text

In [114]:
# Convert the data into a format that numpy will recognize as numeric

# First display the strings data set

loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [116]:
# Change the strings into integers

loan_data_strings = loan_data_strings.astype(np.int)

loan_data_strings

C:\Users\hp pc\AppData\Local\Temp\ipykernel_4900\3623372542.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_strings = loan_data_strings.astype(np.int)


array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [117]:
# Create a checkpoint for all the changes made

checkpoint_strings = checkpoint("checkpoint-strings", header_strings, loan_data_strings)

In [118]:
checkpoint_strings["header"]

array(['Issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [119]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [121]:
# To be 100% sure that the values in the checkpoint are equal to the processed data

np.array_equal(checkpoint_strings['data'], loan_data_strings)

True

In [122]:
# Next is to clean and preprocess the numeric data

loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [123]:
# First check if there are missing values in the array

np.isnan(loan_data_numeric).sum()

0

In [124]:
# The output above is zero, hence no missing value
# Recall we already used filler values to fill the missing value

# Check the headers of the numeric values

header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [125]:
# Check each of the columns, to know which contains the filler temporary value used earlier

np.isin(loan_data_numeric[:,0], temporary_fill)

array([False, False, False, ..., False, False, False])

In [126]:
np.isin(loan_data_numeric[:,0], temporary_fill).sum() # The sum() function returns zero as number of times temporary_fill featured in the array

0

In [127]:
# Check the header_numeric again
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [130]:
#The only column where minimum value can be considered worse is the funded_amnt, and others will be considered for maximum 
#...recorded value
# Recall we already stored the min and max values in the temporary_stats variable computed earlier

temporary_stats[:, columns_numeric]


array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [131]:
# The first row in the array above is the temporary min values, the middle row is temporary mean 
# while the last row is temporary max values

# We will be setting the  temporary filler_values to minimum in the funded_amnt column

# Check the values in the funded_amnt column

loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [133]:
# Setting the temporary_fill values to minimum in the funded amount column

loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill, temporary_stats[0, columns_numeric[2]],
                                  loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [137]:
# Temporary stat also contain the min, mean, and max of string columns
# Display the fourth individual element of temporary min with index of 3, the output is nan because this was stored...
#... before the loan status was processed to numeric
temporary_stats[0,3]

nan

In [138]:
# Checking the min of the fourth numeric column (interest_rate)
temporary_stats[0, columns_numeric[3]]

6.0

In [139]:
# Filling out the remaining numeric columns according to the Head of Data Analytics' casting direction
# Set the max values for loan_amount, interest_rate, installment, and total_payment

# These appears in column index 1, 3, 4, and 5 in the output below

header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [140]:
# Use 'for loop' function to avoid typing 'where' function four times

# This will set temporary_fill values to maximum temporary stats

for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill, temporary_stats[2, columns_numeric[i]], 
                                     loan_data_numeric[:,i])
    

In [141]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

In [144]:
# Convert the exchange rate from USD to Euro

# Import exchange rate converter file 

EUR_USD = np.genfromtxt("EUR-USD.csv", delimiter = ',', autostrip = True)
EUR_USD

array([[ nan,  nan,  nan,  nan,  nan],
       [1.21, 1.21, 1.11, 1.13, 0.  ],
       [1.13, 1.15, 1.12, 1.12, 0.  ],
       [1.12, 1.12, 1.05, 1.08, 0.  ],
       [1.07, 1.12, 1.05, 1.11, 0.  ],
       [1.12, 1.15, 1.08, 1.1 , 0.  ],
       [1.1 , 1.14, 1.09, 1.12, 0.  ],
       [1.11, 1.12, 1.08, 1.09, 0.  ],
       [1.1 , 1.17, 1.09, 1.13, 0.  ],
       [1.12, 1.15, 1.11, 1.13, 0.  ],
       [1.12, 1.15, 1.09, 1.1 , 0.  ],
       [1.1 , 1.11, 1.06, 1.06, 0.  ],
       [1.06, 1.11, 1.05, 1.09, 0.  ]])

In [145]:
# The output above showed nan in the first row which will probably be the names of the column. Set the datatype to strings

EUR_USD = np.genfromtxt("EUR-USD.csv", delimiter = ',', autostrip = True, dtype = str)
EUR_USD

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814',
        '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267',
        '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778',
        '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512',
        '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128',
        '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347',
        '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524

In [146]:
# Each column above represents 'Open', 'High', 'Close', and 'Volume'.
# We are interested in only the adjusted closing price, hence we will limit the data to the fourth column (index 3)

EUR_USD = np.genfromtxt("EUR-USD.csv", delimiter = ',', autostrip = True, skip_header = 1, usecols = 3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [147]:
# Setting exchange rates for the different months

# Recall the date (in months) is in the first column
header_strings[0]

'Issue_date'

In [148]:
# The output below are the numbers representing months from missing (0) to december (12)
loan_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [151]:
# Using loop to set the exchange rate for each month

exchange_rate = loan_data_strings[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i, EUR_USD[i-1], exchange_rate)
    
# For the missing month 0, exchange rate will be the mean 

exchange_rate = np.where(exchange_rate == 0, np.mean(EUR_USD), exchange_rate)

exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [153]:
# We need to add this new array to the dataset
# we need to check if the new variable and the loan_data_numeric have compatible shape

exchange_rate.shape

(10000,)

In [154]:
loan_data_numeric.shape

(10000, 6)

In [155]:
# The shape of exchange_rate is 1-dimensional while numeric dataset is 2-dimensional
# Reshape exchange rate to 2-D

exchange_rate = np.reshape(exchange_rate, (10000,1))

In [156]:
# Use horizontal stacking function, hstack

np.hstack((loan_data_numeric, exchange_rate))

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [157]:
loan_data_numeric = np.hstack((loan_data_numeric, exchange_rate))

In [159]:
# Add the new exchange rate column to the header

header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [160]:
# Four columns contains values in US dollars; loan_amnt, funded-amnt, installment, and total_pymnt

columns_dollar = np.array([1,2,4,5])

loan_data_numeric[:, [columns_dollar]]

array([[[35000.  , 35000.  ,  1184.86,  9452.96]],

       [[30000.  , 30000.  ,   938.57,  4679.7 ]],

       [[15000.  , 15000.  ,   494.86,  1969.83]],

       ...,

       [[10000.  , 10000.  ,  1372.97,  2185.64]],

       [[35000.  , 10000.  ,   354.3 ,  3199.4 ]],

       [[10000.  , 10000.  ,   309.97,   301.9 ]]])

In [164]:
# Exchange rate is in loan_data_numeric[:,6]
# Divide by the exchange rate to get the value in Euro
# Reshape the exchange rate to similar 2-Dimension
 
for i in columns_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i] / 
                                                                 loan_data_numeric[:,6], (10000, 1))))

In [165]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [167]:
# To check if we have new columns to the array
# The output is 10000 by 11 array
loan_data_numeric.shape

(10000, 11)

In [168]:
# We need to update the header since there are new columns to the dataset

header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollar]])

In [169]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [171]:
# Add the additional header to header numeric

header_numeric = np.concatenate((header_numeric, header_additional ))

In [172]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [173]:
# Update the default columns to show they are in USD

header_numeric[columns_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[columns_dollar]])

header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [175]:
# Rearrange the columns so that each Euro column follows its corresponding USD column

columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

header_numeric[columns_index_order]

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [176]:
header_numeric = header_numeric[columns_index_order]

In [177]:
# Set loan_data_numeric in the same index order

loan_data_numeric = loan_data_numeric[:, columns_index_order]

In [178]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

In [179]:
# All missing values have been filled, and exchange rates added for each applicant
# The only column remaining is the interest rate

header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [180]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [182]:
# Transform the interest rate column for the values to be between 0 and 1

loan_data_numeric[:,5] = loan_data_numeric[:,5]/100
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

In [183]:
# Create a checkpoint for all the preprocessed numeric values 

checkpoint_numeric = checkpoint("checkpoint-numeric", header_numeric, loan_data_numeric)

In [184]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

In [185]:
# Combine the preprocessed versions of the string and numeric matrices to create a large dataset
# The two arrays must have compatible shapes

checkpoint_strings['data'].shape # the output is 10000 rows and 6 columns

(10000, 6)

In [186]:
checkpoint_numeric['data'].shape # the output is 10000 rows and 11 columns

(10000, 11)

In [187]:
# We can stack side by side since they have the same number of rows

np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [188]:
# To check if the output is correct

np.hstack((checkpoint_numeric['data'], checkpoint_strings['data'])).shape # 17 columns: 6 from strings and 11 from numeric

(10000, 17)

In [190]:
# Store the output in a new variable 

loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [191]:
# Confirm there is no missing value in the array
# The 0 output confirmed the preprocessing was done correctly

np.isnan(loan_data).sum()

0

In [193]:
# Combine the headers of the two array

header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))

header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'Issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [194]:
# Its a good practice to arrange all the entries according to index variable which is the id
loan_data[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [195]:
loan_data = loan_data[np.argsort(loan_data[:,0])]
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [196]:
np.argsort(loan_data[:,0]) # The output showed it was sorted

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

In [198]:
# Stack the header on top of the sorted data
loan_data = np.vstack((header_full, loan_data))

loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [199]:
# Finally, save the new dataset 

np.savetxt("loan-data-preprocessed.csv", loan_data,
          fmt = "%s", delimiter = ',')                 #This will be saved externally in the directory of the Python app

In [ ]:
# The dataset is now cleaned, preprocessed, and ready for further analysis
# The data science team can take this dataset and prepare a credit risk model (CRM) for estimating probability of default